spring:
  datasource:
    url: jdbc:h2:file:./kafkahelper
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  kafka:
    producer:
      allow-auto-create-topics: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
